name: hakai
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter
  english_words: 4.0.0
  provider: 6.1.2
  firebase_auth: 5.4.0
  cloud_firestore: 5.6.1
  firebase_storage: 12.4.0
  firebase_core: 3.10.0
  cloud_functions: 5.3.0 
  image_picker: 1.1.2 
  image_picker_for_web: 3.0.6
  flutter_colorpicker: 1.1.0
  flutter_quill: 10.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true