name: hakai
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.1
  firebase_auth: 5.4.0
  cloud_firestore: 5.6.1
  firebase_storage: 12.4.0
  firebase_core: 3.10.0
  cloud_functions: 5.3.0 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true