// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVpdVoA11R6h2dQlaTgb5drabArHTHuEQ',
    appId: '1:181704805074:web:db91935565a3991c133b0b',
    messagingSenderId: '181704805074',
    projectId: 'hakai-app-fd2ef',
    authDomain: 'hakai-app-fd2ef.firebaseapp.com',
    storageBucket: 'hakai-app-fd2ef.firebasestorage.app',
    measurementId: 'G-ZGXHMT73GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3pKNNrtQiJk-bOYMrNrjgT_p5QctqdM',
    appId: '1:181704805074:android:62b24d41cf4f3d64133b0b',
    messagingSenderId: '181704805074',
    projectId: 'hakai-app-fd2ef',
    storageBucket: 'hakai-app-fd2ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoTIMOmhz9e_uFLtCquvEGd8bIpmCjgDY',
    appId: '1:181704805074:ios:e655ddd5d43e3175133b0b',
    messagingSenderId: '181704805074',
    projectId: 'hakai-app-fd2ef',
    storageBucket: 'hakai-app-fd2ef.firebasestorage.app',
    iosBundleId: 'com.example.inboxz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoTIMOmhz9e_uFLtCquvEGd8bIpmCjgDY',
    appId: '1:181704805074:ios:e655ddd5d43e3175133b0b',
    messagingSenderId: '181704805074',
    projectId: 'hakai-app-fd2ef',
    storageBucket: 'hakai-app-fd2ef.firebasestorage.app',
    iosBundleId: 'com.example.inboxz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVpdVoA11R6h2dQlaTgb5drabArHTHuEQ',
    appId: '1:181704805074:web:f45ffd9efb97d970133b0b',
    messagingSenderId: '181704805074',
    projectId: 'hakai-app-fd2ef',
    authDomain: 'hakai-app-fd2ef.firebaseapp.com',
    storageBucket: 'hakai-app-fd2ef.firebasestorage.app',
    measurementId: 'G-4VENEVXX6S',
  );
}
